node {
  checkout scm
}

pipeline {
    agent any

    options {
        disableConcurrentBuilds()
        skipDefaultCheckout false
        timeout(time: 60, unit: 'MINUTES')
    }

    stages {
        stage('Creds') {
            steps {
            	 sh "aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 483452016940.dkr.ecr.eu-west-1.amazonaws.com"			
		}
        }
	stage('build') {
            steps {
        	 sh "docker build -t goapp ."
		}
        }
        stage('deploy') {
	    steps {
		sh "docker tag goapp:latest 483452016940.dkr.ecr.eu-west-1.amazonaws.com/goapp:latest"
		sh "docker push 483452016940.dkr.ecr.eu-west-1.amazonaws.com/goapp:latest"
		}
        }
    }
}
